common:
  namespace: mysql

mysql:
  image:
    name: mysql
    repository: mysql
    version: 8.0

  secrets:
    MYSQL_ROOT_PASSWORD: "1234"
    MYSQL_USER: "app_user"
    MYSQL_PASSWORD: "1234"

  statefulSet:
    replicas: 2

  resources:
    requests:
      cpu: "500m"
      memory: "1Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  pvc:
    requests:
      storage: 2Gi
