apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.common.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
